import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#5b403a",
        "surface-variant": "#e5e2e1",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#3c0800",
        background: "#fcf9f8",
        "on-surface": "#1c1b1b",
        "on-error": "#ffffff",
        primary: "#af2900",
        "on-tertiary-fixed": "#002111",
        "surface-tint": "#b32a00",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb4a2",
        "secondary-container": "#b0ecd6",
        "primary-container": "#d63c10",
        "on-tertiary-fixed-variant": "#005232",
        "surface-container-high": "#ebe7e7",
        "inverse-on-surface": "#f3f0ef",
        "error-container": "#ffdad6",
        "on-secondary-container": "#336d5b",
        "surface-container-lowest": "#ffffff",
        tertiary: "#006a42",
        "primary-fixed": "#ffdbd2",
        "secondary-fixed": "#b3efd9",
        outline: "#8f7068",
        "tertiary-container": "#008654",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed": "#002118",
        "tertiary-fixed": "#78fbb6",
        "tertiary-fixed-dim": "#59de9b",
        secondary: "#2f6857",
        "on-tertiary-container": "#f6fff5",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "outline-variant": "#e4beb5",
        error: "#ba1a1a",
        "on-primary-container": "#fffbff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-background": "#1c1b1b",
        "on-secondary-fixed-variant": "#125040",
        "surface-container": "#f0edec",
        "secondary-fixed-dim": "#98d3bd",
        "surface-dim": "#dcd9d9",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#313030",
        "on-primary-fixed-variant": "#891e00",
        "inverse-primary": "#ffb4a2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "1rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "margin-desktop": "3rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        gutter: "1rem",
      },
      fontFamily: {
        "body-sm": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "mono-spec": ["Space Mono", "monospace"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "mono-index": ["Space Mono", "monospace"],
        "display-hero-mobile": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "display-hero": [
          "88px",
          { lineHeight: "84px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "headline-lg": [
          "36px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" },
        ],
        "headline-xl-mobile": [
          "32px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "mono-spec": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "headline-xl": [
          "56px",
          { lineHeight: "58px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "mono-index": [
          "20px",
          { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-hero-mobile": [
          "44px",
          { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
      },
      gridTemplateColumns: {
        "14": "repeat(14, minmax(0, 1fr))",
      },
    },
  },
  plugins: [],
};

export default config;
